//sample to create a single transition node -> node
class Transition {
    constructor (from, symbols, to) {
        this.from = from;
        this.symbols = symbols;
        this.to = to;
    }
}

//sample to create a valid acceptor
class Acceptor {
    constructor() {
        this.transitions = [];
        this.startState = null;
        this.acceptedStates = [];
    }

    //works through a word and returns whether the path is accepted or not NO ERROR HANDLING
    runAcceptor(word){
        turnOff();
        let currentState = this.startState;
        var edges =  cy.json().elements.edges;
        var nodes = cy.json().elements.nodes;

        if(this.startState === null) {
            return {"accepted" : false, "exception" : "startState not defined"};
        }

        if(this.acceptedStates.length === 0) {
            return {"accepted" : false, "exception" : "acceptedStates not defined"};
        }

        for (let position = 0; position < word.length; position++) {
            const symbolInPosition = word[position];

            const matchingTransition = this.transitions.find(
                (f) => f.from === currentState && f.symbols.includes(symbolInPosition)
            );

            if (!matchingTransition) {
                return {"accepted": false, "exception": "transition at state " + currentState + " is missing for symbol " + symbolInPosition};
            }
            currentState = matchingTransition.to;
        }
        if (this.acceptedStates.includes(currentState)) {
            return {"accepted" : true}
        }
        else {
            return {"accepted" : false};
        }
    }

    //fills Acceptor object with data generated by the graph
    refreshFromGraph() {
        this.transitions = [];
        this.startState = null;
        this.acceptedStates = [];

        var edges =  cy.json().elements.edges;
        var nodes = cy.json().elements.nodes;

        for (let n = 0; n < nodes.length; n++){
            if(nodes[n].data.isInitial === true){
                this.startState = nodes[n].data.id;
            }
        }

        for (let n = 0; n < nodes.length; n++){
            if(nodes[n].data.isFinal === true){
                this.acceptedStates.push(nodes[n].data.id);
            }
        }

        for (let e = 0; e < edges.length; e++){
            this.transitions.push(new Transition(edges[e].data.source, edges[e].data.inputList, edges[e].data.target));
        }
    }
}
let ACCEPTOR = new Acceptor();

//runs a single word and prints result
var checkWordAndPrint = function(word) {
    ACCEPTOR.refreshFromGraph()

    var result = ACCEPTOR.runAcceptor(word);

    console.log(result);
    return result;
}