//sample to create a single transition node -> node
class Transition {
    constructor (from, symbol, to) {
        this.from = from;
        this.symbol = symbol;
        this.to = to;
    }
}

//sample to create a valid acceptor
class Acceptor {
    constructor() {
        this.transitions = [];
        this.startState = null;
        this.acceptedStates = [];
    }

    //works through a word and returns whether the path is accepted or not NO ERROR HANDLING
    runAcceptor(word){
        let currentState = this.startState;

        for (let position = 0; position < word.length; position++){
            const symbolInPosition = word[position]
            const matchingTransition = this.transitions.find((f) => f.from === currentState && f.symbol === symbolInPosition);

            if (!matchingTransition) {
                return {"accepted" : false, "exception" : "transition at state " + currentState + " is missing for " + " symbol" + symbolInPosition + " ."};
            }

            if (this.acceptedStates.includes(matchingTransition.to)) {
                return {"accepted" : true}
            }

            currentState = matchingTransition.to;
        }
        return {"accepted" : false};
    }

    //fills Acceptor object with data generated by the graph
    refreshFromGraph() {
        this.transitions = [];
        this.startState = null;
        this.acceptedStates = [];

        var edges =  cy.json().elements.edges;
        var nodes = cy.json().elements.nodes;

        for (let n = 0; n < nodes.length; n++){
            if(nodes[n].data.isInitial === true){
                this.startState = nodes[n].data.id;
            }
        }

        for (let n = 0; n < nodes.length; n++){
            if(nodes[n].data.isFinal === true){
                this.acceptedStates.push(nodes[n].data.id);
            }
        }

        for (let e = 0; e < edges.length; e++){
            this.transitions.push(new Transition(edges[e].data.source, edges[e].data.label, edges[e].data.target));
        }
    }
}

//runs a single word and prints result
var checkWordAndPrint = function(word) {
    let ACCEPTOR = new Acceptor();
    ACCEPTOR.refreshFromGraph()

    var result = ACCEPTOR.runAcceptor(word);

    console.log("Word is" + (result.accepted ? " accepted." : " not accepted."));
}